"use client";

import type { ConservationReport as ReportType } from "@/types";

interface ConservationReportProps {
  report: ReportType;
}

export default function ConservationReportCard({ report }: ConservationReportProps) {
  return (
    <div className="glass-panel p-6 sm:p-8">
      <h3 className="text-lg font-semibold text-reef-teal">
        Conservation Report
      </h3>
      <p className="mt-4 leading-relaxed text-slate-300">{report.executive_summary}</p>

      {report.key_threats.length > 0 && (
        <div className="mt-6">
          <h4 className="text-sm font-medium text-slate-400">Key Threats</h4>
          <ul className="mt-2 list-inside list-disc text-slate-300">
            {report.key_threats.map((t, i) => (
              <li key={i}>{t}</li>
            ))}
          </ul>
        </div>
      )}

      <div className="mt-8 grid gap-8 md:grid-cols-2">
        <div>
          <h4 className="font-medium text-orange-400">Immediate Actions</h4>
          <ol className="mt-3 list-decimal space-y-2 pl-5 text-slate-300">
            {report.immediate_actions.map((a, i) => (
              <li key={i}>{a}</li>
            ))}
          </ol>
        </div>
        <div>
          <h4 className="font-medium text-emerald-400">Preventive Measures</h4>
          <ol className="mt-3 list-decimal space-y-2 pl-5 text-slate-300">
            {report.preventive_measures.map((m, i) => (
              <li key={i}>{m}</li>
            ))}
          </ol>
        </div>
      </div>

      <div className="mt-8 grid gap-4 sm:grid-cols-2">
        <div className="rounded-lg bg-ocean-800/60 p-4">
          <h4 className="text-sm text-slate-400">Monitoring Schedule</h4>
          <p className="mt-2 text-slate-200">{report.monitoring_schedule}</p>
        </div>
        <div className="rounded-lg bg-ocean-800/60 p-4">
          <h4 className="text-sm text-slate-400">Recovery Prognosis</h4>
          <p className="mt-2 text-slate-200">{report.recovery_prognosis}</p>
        </div>
      </div>

      {report.scientific_context && (
        <p className="mt-6 text-sm italic text-slate-500">{report.scientific_context}</p>
      )}

      <p className="mt-6 text-xs text-slate-600">
        Generated by Groq LLM
      </p>
    </div>
  );
}
